version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: chicken-poop-bingo-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: chicken_poop_bingo
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password_123}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - chicken-poop-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d chicken_poop_bingo"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Main Application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chicken-poop-bingo-app
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://app_user:${DB_PASSWORD:-secure_password_123}@database:5432/chicken_poop_bingo
      # Add your Stripe keys here
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      VITE_STRIPE_PUBLIC_KEY: ${VITE_STRIPE_PUBLIC_KEY}
    ports:
      - "5000:5000"
    networks:
      - chicken-poop-network
    volumes:
      # Mount logs directory for persistence
      - app_logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/game"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: chicken-poop-bingo-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - chicken-poop-network

volumes:
  postgres_data:
    driver: local
  app_logs:
    driver: local

networks:
  chicken-poop-network:
    driver: bridge